# Generated by Django 5.2.4 on 2025-07-19 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        max_length=255, verbose_name="Nome original do arquivo"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do arquivo (bytes)"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="Duração"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt-BR", "Português (Brasil)"),
                            ("en-US", "Inglês (EUA)"),
                            ("es-ES", "Espanhol"),
                            ("fr-FR", "Francês"),
                            ("de-DE", "Alemão"),
                        ],
                        default="pt-BR",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processing", "Processando"),
                            ("completed", "Concluída"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="Progresso (%)"),
                ),
                (
                    "transcription_text",
                    models.TextField(blank=True, verbose_name="Texto transcrito"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Pontuação de confiança"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transcrição",
                "verbose_name_plural": "Transcrições",
                "ordering": ["-created_at"],
            },
        ),
    ]
